### ISSUE TITLE
How the logic of operation was derived?

### ISSUE THREAD

**Issue by ogamespec** [nukeykt/Nuked-PSG#3]
Привет, интересно как удалось получить логику работы PSG. Изучением фотографии VDP циркулирующих в сети или чтением даташита? Мы тут затеяли проект по восстановлению схемы PSG по фотографии чипа, может уже всё сделано? :)

Hi, I wonder how you managed to get the logic of the PSG to work. By studying pictures of VDPs circulating in the network or by reading the datasheet? We have started a project to reconstruct the PSG circuit from the chip photo, maybe it's already done? :)

(not actually Issue)

**Comment by nukeykt** [comment]
Привет :)
Ага, код был написан используя [эти фотки](https://www.grafik-feti.de/ftp/Die-Shots/Archiv/2D/Die-Shots/GamingConsoles/SEGA_Genesis_MegaDrive/MD1/VDP/). Как таковые схемы я не составлял, обычно я все в голове держу и делаю небольшие заметки в inkscape поверх фотки. Разобравшись с каким либо участком пишу логику на C (c FPGA не знаком пока что).
Можешь наверное мне в discord написать: nukeykt#0449 . Сейчас наверное и не вспомню все детали, но попробую ответить на вопросы.

**Comment by ogamespec** [comment]
Спасибо! Связался :)
